baseURL = 'https://lucabruzzone.me/'
languageCode = 'en-us'
title = "Random thoughts and ideas"
theme = 'ananke'
copyright="All content is under CC BY-SA license. Luca Bruzzone"

[params]
  text_color = ""
  author = "Luca Bruzzone"
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3

[[params.ananke_socials]]
  name = "About me / GDPR / T&C"
  url = "/about-gdpr-tc"

[[params.ananke_socials]]
  name = "mastodon"
  url = "https://mstdn.social/@unsigned"

[[params.ananke_socials]]
  name = "github"
  url = "https://github.com/unsign3d"
  
